# pyright: reportUnknownVariableType=false, reportUnknownMemberType=false
# pyright: reportUnknownArgumentType=false
# Generated by Django 6.0.2 on 2026-02-18 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_is_published_to_access_type(apps, schema_editor):  # type: ignore[no-untyped-def]
    Questionnaire = apps.get_model("data", "Questionnaire")
    Questionnaire.objects.filter(is_published=True).update(access_type="public")
    Questionnaire.objects.filter(is_published=False).update(access_type="draft")


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0004_populate_site_and_flatpages"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaire",
            name="access_type",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("public", "Public"),
                    ("private", "Private"),
                    ("invite_only", "Invite Only"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            migrate_is_published_to_access_type,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="questionnaire",
            name="is_published",
        ),
        migrations.CreateModel(
            name="QuestionnaireInvite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invited_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questionnaire_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="data.questionnaire",
                    ),
                ),
            ],
            options={
                "db_table": "questionnaire_invites",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("questionnaire", "invited_user"),
                        name="unique_questionnaire_invite",
                    )
                ],
            },
        ),
    ]
